language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install libboost1.53-all-dev
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd -

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - make
