language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8
  - sudo apt-get install libstdc++6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50

install:
  - sudo apt-get install libboost1.55-all-dev
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd -

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - make
